### ISSUE TITLE
Implement Hexadecimal conversion model(convert from base16 to base10 and vice versa)

### ISSUE THREAD

**Issue by mrbrianevans** [mrbrianevans/number-format-converter#15] opened 2020-12-03 15:33 UTC
#### The model is located here "./functions/src/model/hexadecimal.ts"
1. Algorithm to convert from base16 to base10
2. Algorithm to convert from base10 to base16

To contribute, read the contribution docs [Contribution docs](https://github.com/mrbrianevans/number-format-converter/blob/master/contributing.md)
Be sure to write the actual algorithms and not use built in conversion functions.

**Comment by 0xWaleed** [comment] 2020-12-11 19:26
Hi, I ended up doing this, 
```typescript

 let result: string = '';
        let r = 0;
        while (decimal != 0) {

            // r = decimal % 16 + r;
            r = (decimal ) & 0xF;
            if (r >= 10 && r <= 15) {
                result += String.fromCharCode(65 + (r - 10));
                console.log('hex:', result);
            }else {
                result += String.fromCharCode(48 + r);
                console.log('dec:', result);
            }
            decimal >>= 4;
        }

//result should be reversed
        return result;
```
The problem is the result will contained hexadecimal value in reverse and I am not sure how to solve that without using
builtin functions.. I am not familiar with math advanced functions.. and found that as a challenge.. any help ?

**Comment by DanielRomeo** [comment] 2020-12-11 19:34
Hey @0xWaleed  , What I meant was you arent allowed to use built in **Converter** functions such as :

```javascript
hexString = yourNumber.toString(16);
``` 


however, regular typescript/javascript functionality such as 'reversing a string' like:
```typescript
function reverse(s){
    return s.split("").reverse().join("");
}
```
 is allowed.

**Comment by DanielRomeo** [comment] 2020-12-11 19:38
I hope that makes sense. But to give you a quick solution for your problem; you could just loop through the string backwards and add each charector into a new array... Then return that new array.

However, you are free to do anything you want / any method you want 👍🏾

**Comment by 0xWaleed** [comment] 2020-12-11 19:54
Thanks, I solved as fast as it works. my point is to get familiar with Github and the contribution system.
usually I solve problem by covering it in test and keep the refactor later. but hope my last commit satisfy the requirement.
🤷🏻

**Comment by DanielRomeo** [comment] 2020-12-11 19:58
@0xWaleed , Thanks, yes I tested it myself and it  works. Thanks for also writing the Test.

It has been merged. 🚀

**Closed** 2020-12-11 20:00 UTC
Labels: algorithm, beginner, good first issue, help wanted, new-format
